name = "TurbulentPropagation"
uuid = "1a5b2b60-f6fa-4862-8c4f-ce00f8badc9a"
authors = ["Marcos Gil <marcosgildeoliveira@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
FFTW = "1.9.0"
KernelAbstractions = "0.9.38"
Random = "1.11.0"
